# Generated by Django 5.2 on 2025-07-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="size",
            new_name="file_size",
        ),
        migrations.RenameField(
            model_name="fileupload",
            old_name="file_name",
            new_name="original_file_name",
        ),
        migrations.AddField(
            model_name="fileupload",
            name="encryption_key",
            field=models.TextField(default="r6r8364wudhiuid63SEGYRTY576hvh"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="encrypted_file",
            field=models.FileField(upload_to="encrypted_files/"),
        ),
    ]
